### PR TITLE
Fixed warnings not being logged to console

### LINKED ISSUE #23: Warnings not being logged to console
Rules with a severity of "warning" are not logged to the console unless a linting error has also occurred.

If there are only warnings in your styles then no output is logged to the console at all.

### PR DESCRIPTION
**Pull request by iblack10**
Warnings were not being logged unless there was an error in the css linting.

Fixes #23

### CODE REVIEW

**Comment by JaKXz** [comment]
Thanks for the PR @iblack10, it looks reasonable to me :) would you mind adding a fixture that would provide a warning and a test that ensures the warnings are printed?

**Comment by iblack10** [comment]
Hope that's OK - seemed that the plugin wasn't actually carrying any warnings through from stylelint.

**Comment by JaKXz** [comment]
This will need to be rebased before merging :)

File: lib/run-compilation.js [hunk 1]
```diff
@@ -49,5 +55,8 @@ module.exports = function runCompilation(options, compilation, done) {
     errors.forEach(function (err) {
       compilation.errors.push(err);
     });
+    warnings.forEach(function (warning) {
+      compilation.warnings.push(warning);
```
Comment (JaKXz) [inline lib/run-compilation.js]: Please use the `.concat` method instead of going through each warning. I've been meaning to fix the original code as well so if you could change it that'd be great.

**Comment by iblack10** [comment]
Looking at this further I think there are some problems with the tests. Test 8 should actually have zero errors but it's reporting 1. Seems like the .map function means that even if there are no errors or warnings it will return the source of the file being tested resulting in the length of the error/warning array never being zero. I'll take another look tomorrow.

**Comment by iblack10** [comment]
I'm hopeful that's everything sorted now. Sorry there are so many commits inside of this pull request - pretty new to Github!

**Comment by JaKXz** [comment]
Thanks @iblack10 this is great so far. If there are other cases you could add with other fixtures, could you add them or let me know otherwise? I'll merge after that :)

**Comment by iblack10** [comment]
Great, I think that's all for now - it's working well for me!

**Comment by JaKXz** [comment]
Thanks again @iblack10, I'll have the `0.3.1` release out tomorrow. Feel free to `npm install stylelint-webpack-plugin#master` for now, I just have a big project due tonight.

cc @vieron
